version: '3.7'

services:
  ca.bc-coop.bclan:
    container_name: ca-bclan-network-it
    image: smartbcity/commune-sandbox-ca:latest
    networks:
      - bclannet-it
    ports:
      - 7054:7054

  orderer.bclan:
    container_name: orderer-network-it
    image: smartbcity/commune-sandbox-orderer:latest
    networks:
      - bclannet-it
    ports:
    - 7050:7050

  peer0.bc-coop.bclan:
    container_name: peer0-bclan-network-it
    image: smartbcity/commune-sandbox-peer:latest
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=bclannet-it
    volumes:
      - /var/run/docker.sock:/host/var/run/docker.sock
    networks:
      - bclannet-it
    depends_on:
      - orderer.bclan
    ports:
      - 7051:7051
      - 7053:7053


  cli-init.bc-coop.bclan:
    container_name: cli-init-bclan-network-it
    image: smartbcity/commune-sandbox-cli:latest
    command: /opt/commune-sandbox/util/initEx02.sh
    networks:
      - bclannet-it
    depends_on:
      - peer0.bc-coop.bclan
    volumes:
      - ./infra/dev/chaincode/go/chaincode_example02/chaincode_example02.go:/opt/gopath/src/chaincode_example02/chaincode_example02.go
      - ./infra/dev/chaincode/initEx02.sh:/opt/commune-sandbox/util/initEx02.sh

networks:
  bclannet-it:
    name: bclannet-it
