version: '3.7'

services:
  ca.bc-coop.bclan:
    container_name: ca.bc-coop.bclan
    image: civisblockchain/bclan-ca:latest
    ports:
      - 7054:7054
    networks:
      - bclannet-it

  orderer.bclan:
    container_name: orderer.bclan
    image: civisblockchain/bclan-orderer:latest
    ports:
      - 7050:7050
    networks:
      - bclannet-it

  peer0.bc-coop.bclan:
    container_name: peer0.bc-coop.bclan
    image: civisblockchain/bclan-peer:latest
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=bclannet-it
    volumes:
      - /var/run/docker.sock:/host/var/run/docker.sock
    ports:
      - 7051:7051
      - 7053:7053
    networks:
      - bclannet-it

  cli-init.bc-coop.bclan:
    container_name: cli-init-bclan-network-it
    image: civisblockchain/bclan-cli:0.3.1-local
    command: /opt/blockchain-coop/util/initEx02.sh
    networks:
      - bclannet-it

networks:
  bclannet-it:
    name: bclannet-it
