version: '2'

services:
  coop-rest-java:
    image: civisblockchain/coop-rest-java
    environment:
      - coop_channel=${channel}
      - coop_ccid=${ccid}
      - coop_user_name=${ca__ADMIN}
      - coop_user_password=${ca__PASSWD}
      - coop_user_org=${ca__ORG}
      - coop_config_file=file:/opt/rest-coop/config.json
      - coop_config_crypto=file:/opt/rest-coop
      - coop_endorsers=${endorsers}
    volumes:
      - ${config_file}:/opt/rest-coop/config.json
      - ${config_crypto}:/opt/rest-coop/crypto-config
    ports:
      - 9090:9090
