package io.civis.blockchain.coop.rest.i2.keycloak.config

import org.springframework.boot.autoconfigure.condition.ConditionalOnProperty
import org.springframework.boot.autoconfigure.security.reactive.ReactiveUserDetailsServiceAutoConfiguration
import org.springframework.context.annotation.Configuration

@Configuration
@ConditionalOnProperty(WebSecurityConfig.conditionalProperty)
class ConditionalReactiveUserDetailsServiceAutoConfiguration: ReactiveUserDetailsServiceAutoConfiguration()