spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${i2.keycloak.auth-server-url}/realms/${i2.keycloak.realm:}
  autoconfigure:
    exclude:
     - org.springframework.boot.autoconfigure.security.oauth2.resource.reactive.ReactiveOAuth2ResourceServerAutoConfiguration